spring:
  messages:
    basename: i18n.login
  main:
    allow-bean-definition-overriding: true
  mvc:
    date-format: yyyy-MM-dd
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.22.134:3306/clouddb02
    username: root
    password: 123456
    druid:
      max-pool-prepared-statement-per-connection-size: 20
      min-idle: 5
      max-active: 20
      test-while-idle: true
      aop-patterns: com.bingo.plan.service.*,com.bingo.plan.dao.*
      filters: stat,wall
      max-wait: 30000
      test-on-borrow: true
      pool-prepared-statements: true
      initial-size: 3
      test-on-return: true
      web-stat-filter:
        session-stat-enable: true
        principal-cookie-name: 
        url-pattern: /*
        session-stat-max-count: 10
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        enabled: true
        profile-enable: 
        principal-session-name: 
      stat-view-servlet:
        allow: 172.20.2.110,127.0.0.1
        deny: 172.20.2.111
        url-pattern: /druid/*
        reset-enable: false
        login-password: admin1
        login-username: admin
        enabled: true
  devtools:
      restart:
        enabled: true
        additional-exclude: src/main
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.yang.entitys
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
  